# Generated by Django 5.1.2 on 2024-12-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothingCleaning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('lavanderia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('servicio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLaundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingDirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('tipo_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clinicalservice')),
                ('tipo_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clinicalservice')),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clothingtype')),
            ],
        ),
        migrations.CreateModel(
            name='DirtyClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('en_proceso', models.BooleanField(default=False)),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clothingtype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clinicalservice')),
                ('laundry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.externallaundry')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingCleanings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clothing')),
                ('lavanderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.externallaundry')),
            ],
        ),
    ]
