# Generated by Django 5.1.2 on 2024-11-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothinginventory',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
