# Generated by Django 5.1.2 on 2024-11-19 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_clothinginventory_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothinginventory',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='clothinginventory',
            name='clothing_status',
        ),
        migrations.RemoveField(
            model_name='clothinginventory',
            name='fecha_transaccion',
        ),
        migrations.RemoveField(
            model_name='clothinginventory',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='clothinginventory',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='clothinginventory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clinicalservice'),
        ),
        migrations.CreateModel(
            name='DirtyClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('en_proceso', models.BooleanField(default=False)),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clothingtype')),
                ('laundry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.externallaundry')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clinicalservice')),
            ],
        ),
    ]
